### ISSUE TITLE
Default favicon showing up in "view file" tab

### ISSUE THREAD

**Issue by ol3mon** [creecros/Customizer#124]
Hi,
First, I would like to thank the creator of the plugin. I'm using other of your plugins too, many thanks !

The issue is related to the **favicon**.
After changing the favicon with the customizer all goes fine, except whene I try to view attached files then the default favion (kb) show up in the new opened file tab.
The main window remain with the custom favicon.

**Comment by creecros** [comment]
try emptying your cache in your browser. if thay oesnt work, ill take a look.

**Comment by creecros** [comment]
@ol3mon nevermind, i tested, you are correct. I will look into it.

**Comment by creecros** [comment]
after a bit of research, this could be tricky. when you view a file, and just shoots it to the browser, there is no header to define the favicon, so it defaults to the favicon.ico in the base dir. 

so, i would have to either, change that behavior, and include a layout to choose the favicon in this scenario or convert the uploaded png for the favicon into an ico and replace that base favicon, not even sure the permissions would allow that tbh. 

either way, both require some work, so, it may be something i can get to in the future.

**Comment by creecros** [comment]
OK, so, this is one of those things where I don't like any option. the only real solution is to replace the favicon.ico in the base directory, and customizer doesn't have the permissions to do that, and to do so, would really be a security threat anyway.

I could create layouts for every one of these instances, but that goes out the window if anyone ever chooses something like "open image in new tab" because it's the same thing, there is no way around it, and so these instances will always exist.

so, the only thing I can think to do, would be to include a png to ico converter and allow people to download their favicon.ico which then, they will have to manually place into the base directory of the app.

**Comment by ol3mon** [comment]
Hi, thanks for your responses, I appreciate it alot !

I've tried to manually raplace the favicon ./assets/img/favicon.png but it keeps showing even after a hard cache clear (ctrl+f5).
also i moved all img there to a subfolder to test out but the default favicon keeps showing.
Is there any other file feeding this favicon ?

**Comment by creecros** [comment]
I said, the "favicon.ico" in the basefolder. not the "favicon.png" in the assets folder.

**Comment by ol3mon** [comment]
yes that was right my mistake. it's works fine
