### ISSUE TITLE
A lot of PHP errors when enabling Customizer

### ISSUE THREAD

**Issue by ntimo** [creecros/Customizer#73]
Hello,
I just installed Customer and I am getting these errors when I try to open any Kanboard page. 
<img width="1486" alt="bildschirmfoto 2018-12-29 um 13 30 10" src="https://user-images.githubusercontent.com/6145026/50538372-04b8b500-0b6f-11e9-88b0-3780f3066142.png">

Kanboard version:  1.2.7
I have the following plugins installed:
Bigboard  
CardPushDate 
Coverimage  
ExtendedMail  
Gantt  
GogsWebhook  
Gravatar  
Milestone  
Nebula  
SendEmailCreator  
Task2pdf  
TaskAssignCategory  
TaskIntervalButton  
Telegram  
Timetrackingeditor  
UpdateNotifier  
Voting
Customizer

Thank you for your help

**Comment by creecros** [comment]
Probably because 1.2.7 is no longer compatible. I'll take a look next chance I get.

**Comment by creecros** [comment]
in case you want to see for yourself:

https://projects.nachostudio.ml/

admin
admin

pretty sure your issue is with your folder permissions, the more I look at it.

**Comment by creecros** [comment]
Oh, and looks like you are using the default for DATA_DIR in your config.php, since it can't find the correct folder, for your DATA. Add the below lines from the default config file in Kanboard to the actual config.php file in Kanboard, define them correctly, and make sure the permissions are correct. Let me know if that solves it.

https://github.com/kanboard/kanboard/blob/master/config.default.php#L9-L10

https://github.com/kanboard/kanboard/blob/master/config.default.php#L21-L22

**Comment by ntimo** [comment]
Hello,
I just changed
```
// Data folder (must be writeable by the web server user and absolute)
define('DATA_DIR', __DIR__.DIRECTORY_SEPARATOR.'data');

// Plugins directory
define('PLUGINS_DIR', 'plugins');
```

to: 
```
// Data folder (must be writeable by the web server user and absolute)
define('DATA_DIR', __DIR__.DIRECTORY_SEPARATOR.'/webcustom/kanboard/data');

// Plugins directory
define('PLUGINS_DIR', '/webcustom/kanboard/plugins');
```


I am using mysql the php version is ```PHP 7.2.13 (cli) (built: Dec 21 2018 02:22:47) ( NTS )```

**Comment by ntimo** [comment]
Closing this manually creating the files/customizer/themes in the data folder fixed the problem :)

**Comment by creecros** [comment]
Awesome, glad you got it to work!
