### ISSUE TITLE
Avatar size setting for cards/tasks

### ISSUE THREAD

**Issue by nekohayo** [creecros/Customizer#89]
The Customizer plugin allows setting the avatar size in the header bar at the top, but what I'm really interested in is to have the same kind of setting available for the size of avatars in the tasks (cards) in the boards, so that we can have something bigger than the pointless 20px default ones. Thanks!

**Comment by creecros** [comment]
well, the back end is there, i feel like there was an original reason as to why i didn't add that option, and it's the second request for it...for the life of me, i can't think of that reason though. When I get a free moment I'll take a look at adding it in the next release.

**Comment by nekohayo** [comment]
Maybe it was because in recent versions Kanboard also shows the full assignee name on the top line, which eats space and wraps around in an ugly fashion, and that the user may want to be able to hide the assignee name text label when the avatars are big enough to replace it? Just a thought :)

**Comment by creecros** [comment]
No, that wasn't it. I think it had to do with selfish reasons...the original request for avatar size came from the forum, and I explained how to do it, but they didn't take initiative.  The next request came in a unrelated pull request to this plugin, and I was more inclined to do it, to prove it could be done, but the request was only for the right corner, so never bothered with the task board. Selfish, right?

**Comment by creecros** [comment]
Only did a quick test, so, let's hope for the best...

**Comment by nekohayo** [comment]
This is aaaaawesome, it looks so much better, thank you! And yeah the configurability is nice; for example, I have set the avatar size to 40px (and rounding to 25%), instead of the max 50px size because in that case when you have tasks with short titles (that use only one line height) and categories or labels, the categories will try to "wrap" around the image instead of being below the image. At 40px then it works.

This kinda raises the question of if the same feature could be exposed for controlling the size of the "Other Assignees" avatars from your https://github.com/creecros/group_assign plugin, but then space constraints kick in and that might become its own feature request (should it be filed onto "group_assign", or on "Customizer"?), as it might entail the ability to hide the "Other Assignees" label (to save space) and main assignee name label, instead offering to show all the avatars as one big line (primary assignee, then the secondary assignees) in a bigger configurable size, like what you see on various other apps out there.

But for the time being, I'm already grateful about the progress that has been made here with the configurable sizing of the main assignee avatar. Thanks!

**Comment by creecros** [comment]
I wouldn't want to add a feature in Customizer that would be useless without the dependent Plugin(i.e. Group_assign), so that would be a feature request for Group_assign. 

I think it would be doable, without looking up the overrides, but both these plugins override massive amounts of templates and bypass helpers, controllers, and models, so there is the possibility there may be a conflict somewhere, no idea until I try.

Also, not sure how quick I would get to that one. I had a pause on my other project, and happened to think this was the easiest feature on my to-do list. 

Still have to:
- Finish DocPHT for first release
- Add Email Comment feature in SendEmailCreator
- Figure out wtf is going on in MetaMagik and Automatic Actions using the OEM models instead of the overrides. (I'm clueless on this one.)
- Add Project dependent Custom Fields to MetaMgik, ugh...
- Some BS requests in Task2PDF that I've ignored for a year, maybe more
- Some BS requests in SubtaskDueDate that I haven't really even looked at.
- Some BS requests in other repo's that I can't even keep track of, maybe in coverimage or backlog-board.

So no promises on how fast I would get to it.

**Comment by nekohayo** [comment]
No problem, I totally understand that there is no promise on implementing this quickly, just thought I'd ask if it's fine for me to refile that "part 2" into a new focused ticket :)

**Comment by creecros** [comment]
Yes, it's no problem ;)
